// sca_hardware_inventory/src/components/footer.vue
<template>
  <footer class="footer mt-auto py-3">
    <div class="container-fluid text-center">
      <span class="text-muted fw-bold opacity-75">
        &copy; {{ currentYear }} DevJMR. All rights reserved.
      </span>
    </div>
  </footer>
</template>

<script setup>
const currentYear = new Date().getFullYear();
</script>

<style scoped>
.footer {
  border-top: 1px solid rgba(0, 0, 0, 0.05);
  background-color: transparent;
}
.footer span {
  font-size: 0.85rem;
  letter-spacing: 0.05rem;
}
</style>

// sca-sitemap-next/app/components/footer.tsx
import React from "react";

export default function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="w-full py-6 mt-auto border-t border-slate-200 bg-slate-50">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center px-4 sm:px-6 lg:px-8 text-sm text-slate-500">
        <p>&copy; {currentYear} DevJMR. All rights reserved.</p>
        <div className="flex gap-4 mt-4 md:mt-0">
          <a
            href="#"
            className="hover:text-slate-900 transition-colors font-medium"
          >
            Privacy Policy
          </a>
          <a
            href="#"
            className="hover:text-slate-900 transition-colors font-medium"
          >
            Terms of Service
          </a>
          <a
            href="#"
            className="hover:text-slate-900 transition-colors font-medium"
          >
            Contact
          </a>
        </div>
      </div>
    </footer>
  );
}
