// capture-image-app/src/components/footer.vue
<script setup>
const year = new Date().getFullYear();
</script>

<style scoped>
.footer a:hover {
  text-decoration: underline;
}
</style>
<template>
  <footer class="footer mt-auto py-3 bg-dark text-light">
    <div class="container">
      <div class="row align-items-center">
        <!-- Left -->
        <div class="col-md-6 text-center text-md-start mb-2 mb-md-0">
          © {{ year }} DevJMR.
        </div>

        <!-- Right -->
        <div class="col-md-6 text-center text-md-end">All rights reserved.</div>
      </div>
    </div>
  </footer>
</template>

// sca-sitemap-jsx/src/components/footer.jsx
const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="w-full bg-white dark:bg-slate-800 border-t border-slate-200 dark:border-slate-700 py-6 px-8 mt-auto">
      <div className="flex flex-col md:flex-row justify-between items-center gap-4">
        <div className="text-slate-500 dark:text-slate-400 text-sm font-medium">
          &copy; {currentYear} SCA App. All rights reserved.
        </div>
        <div className="text-slate-500 dark:text-slate-400 text-sm font-medium flex items-center gap-1">
          Crafted with <span className="text-rose-500 text-lg leading-none">&hearts;</span> by 
          <a href="#" className="text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 font-bold ml-1 transition-colors">
            DevJMR
          </a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
