// sca-sitemap-next/app/login/page.tsx
"use client";

import { useState, FormEvent } from "react";
import { useAuth } from "../context/auth";
import { Package2, Eye, EyeOff, LogIn, AlertCircle } from "lucide-react";

export default function LoginPage() {
  const { login } = useAuth();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");
    setIsLoading(true);
    try {
      await login(username, password);
    } catch (err: any) {
      setError(err.message || "Login failed. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-linear-to-br from-slate-50 via-indigo-50/40 to-purple-50/30 flex items-center justify-center p-4">

      {/* Decorative background blobs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-96 h-96 bg-indigo-200/30 rounded-full blur-3xl" />
        <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-purple-200/20 rounded-full blur-3xl" />
      </div>

      <div className="relative w-full max-w-md">

        {/* Card */}
        <div className="bg-white/80 backdrop-blur-sm border border-slate-200/60 rounded-3xl shadow-xl shadow-slate-200/50 p-8">

          {/* Logo */}
          <div className="flex flex-col items-center mb-8">
            <div className="bg-indigo-600 p-3 rounded-2xl shadow-lg shadow-indigo-500/30 mb-4">
              <Package2 className="w-7 h-7 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-slate-800 tracking-tight">
              SCA<span className="text-indigo-500 font-light">Sitemap</span>
            </h1>
            <p className="text-slate-400 text-sm mt-1">Sign in to your account</p>
          </div>

          {/* Error banner */}
          {error && (
            <div className="flex items-center gap-2.5 bg-red-50 border border-red-200 text-red-600 rounded-xl px-4 py-3 text-sm mb-5">
              <AlertCircle className="w-4 h-4 shrink-0" />
              {error}
            </div>
          )}

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Username */}
            <div>
              <label
                htmlFor="username"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Username
              </label>
              <input
                id="username"
                type="text"
                autoComplete="username"
                required
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="Enter your username"
                className="w-full px-4 py-2.5 rounded-xl border border-slate-200 bg-slate-50 text-slate-800 placeholder-slate-400 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-400 transition-all"
              />
            </div>

            {/* Password */}
            <div>
              <label
                htmlFor="password"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Password
              </label>
              <div className="relative">
                <input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  autoComplete="current-password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Enter your password"
                  className="w-full px-4 py-2.5 pr-11 rounded-xl border border-slate-200 bg-slate-50 text-slate-800 placeholder-slate-400 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-400 transition-all"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword((v) => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 transition-colors"
                  aria-label={showPassword ? "Hide password" : "Show password"}
                >
                  {showPassword ? (
                    <EyeOff className="w-4 h-4" />
                  ) : (
                    <Eye className="w-4 h-4" />
                  )}
                </button>
              </div>
            </div>

            {/* Submit */}
            <button
              id="login-submit-btn"
              type="submit"
              disabled={isLoading}
              className="w-full mt-2 flex items-center justify-center gap-2 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-60 disabled:cursor-not-allowed text-white font-semibold rounded-xl text-sm transition-all shadow-md shadow-indigo-500/20 hover:shadow-indigo-500/30 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
            >
              {isLoading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full animate-spin" />
                  Signing in…
                </>
              ) : (
                <>
                  <LogIn className="w-4 h-4" />
                  Sign In
                </>
              )}
            </button>
          </form>

          {/* Divider hint */}
          <p className="text-center text-xs text-slate-400 mt-6">
            © {new Date().getFullYear()} SCA Sitemap · All rights reserved
          </p>
        </div>
      </div>
    </div>
  );
}

// sca-sitemap-vue/src/views/login.vue
<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import api from "../api/axios";

const router = useRouter();

const email = ref("");
const password = ref("");
const showPassword = ref(false);
const loading = ref(false);
const errorMsg = ref("");

const handleLogin = async () => {
  errorMsg.value = "";
  loading.value = true;
  try {
    const res = await api.post("/api/v1/login", {
      email: email.value,
      password: password.value,
    });
    localStorage.setItem("access_token", res.data.access_token);
    router.push("/dashboard");
  } catch (err) {
    errorMsg.value =
      err.response?.data?.detail || "Login failed. Please try again.";
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <div class="login-page">
    <div
      class="container min-vh-100 d-flex justify-content-center align-items-center py-5"
    >
      <div
        class="card login-card shadow-lg border-0 rounded-4 w-100 overflow-hidden"
        style="max-width: 900px"
      >
        <div class="row g-0">
          <!-- Left Side Branding / Graphic -->
          <div
            class="col-md-5 d-none d-md-block login-sidebar position-relative"
          >
            <div
              class="d-flex flex-column h-100 justify-content-between p-5 text-white position-relative z-1"
            >
              <div>
                <h3 class="fw-bold mb-4 d-flex align-items-center text-white">
                  <i class="bi bi-diagram-3-fill fs-2 me-2"></i>
                  SCA Sitemap
                </h3>
                <p class="lead fw-medium text-white-50">
                  Manage and organize your site structure seamlessly.
                </p>
              </div>

              <div class="mt-auto">
                <p class="small mb-0 text-white-50">
                  &copy; 2026 SCA Sitemap. All rights reserved.
                </p>
              </div>
            </div>
            <!-- Background Decoration -->
            <div
              class="bg-decoration position-absolute top-0 start-0 w-100 h-100"
            ></div>
          </div>

          <!-- Right Side Login Form -->
          <div class="col-md-7 col-12 bg-white">
            <div
              class="card-body p-4 p-sm-5 d-flex flex-column justify-content-center h-100 ps-xl-5 pe-xl-5"
            >
              <router-link
                to="/"
                class="text-decoration-none text-muted mb-4 d-inline-block fw-semibold"
                style="transition: color 0.2s"
              >
                <i class="bi bi-arrow-left me-1"></i> Back to User Selection
              </router-link>
              <div class="mb-5">
                <div class="d-md-none text-primary mb-3 text-center">
                  <i class="bi bi-diagram-3-fill fs-1"></i>
                  <h3 class="fw-bold mt-2">SCA Sitemap</h3>
                </div>
                <h2 class="fw-bold text-dark mb-2">Welcome back!</h2>
                <p class="text-muted">Please enter your details to sign in.</p>
              </div>

              <form @submit.prevent="handleLogin">
                <!-- Error Alert -->
                <div
                  v-if="errorMsg"
                  class="alert alert-danger alert-dismissible fade show rounded-3 py-2 px-3 d-flex align-items-center"
                  role="alert"
                >
                  <i class="bi bi-exclamation-circle me-2"></i>
                  <span class="small">{{ errorMsg }}</span>
                  <button
                    type="button"
                    class="btn-close btn-close-sm ms-auto"
                    @click="errorMsg = ''"
                    aria-label="Close"
                    style="font-size: 0.65rem"
                  ></button>
                </div>

                <div class="form-floating mb-3">
                  <input
                    v-model="email"
                    type="email"
                    class="form-control bg-light border-0 shadow-none"
                    id="floatingInputEmail"
                    placeholder="name@example.com"
                    required
                  />
                  <label for="floatingInputEmail" class="text-muted"
                    >Email address</label
                  >
                </div>

                <div class="form-floating mb-3 position-relative">
                  <input
                    v-model="password"
                    :type="showPassword ? 'text' : 'password'"
                    class="form-control bg-light border-0 shadow-none"
                    id="floatingInputPassword"
                    placeholder="Password"
                    required
                  />
                  <label for="floatingInputPassword" class="text-muted"
                    >Password</label
                  >
                  <button
                    type="button"
                    class="btn btn-link position-absolute end-0 top-50 translate-middle-y text-decoration-none text-muted"
                    @click="showPassword = !showPassword"
                    tabindex="-1"
                  >
                    <i
                      :class="
                        showPassword ? 'bi bi-eye-slash-fill' : 'bi bi-eye-fill'
                      "
                    ></i>
                  </button>
                </div>

                <div
                  class="d-flex justify-content-between align-items-center mb-4"
                >
                  <div class="form-check">
                    <input
                      class="form-check-input shadow-sm"
                      type="checkbox"
                      id="rememberMe"
                    />
                    <label
                      class="form-check-label text-muted small user-select-none"
                      for="rememberMe"
                    >
                      Remember for 30 days
                    </label>
                  </div>
                  <router-link
                    to="/forgot-password"
                    class="text-primary small text-decoration-none fw-semibold"
                    >Forgot Password?</router-link
                  >
                </div>

                <div class="d-grid mb-4">
                  <button
                    type="submit"
                    class="btn btn-primary btn-lg rounded-3 fw-bold shadow-sm login-btn py-3"
                    :disabled="loading"
                  >
                    <span
                      v-if="loading"
                      class="spinner-border spinner-border-sm me-2"
                      role="status"
                      aria-hidden="true"
                    ></span>
                    {{ loading ? "Signing In..." : "Sign In" }}
                  </button>
                </div>

                <!-- <div class="position-relative mb-4 text-center mt-4">
                   <hr class="text-muted">
                   <span class="position-absolute top-50 start-50 translate-middle bg-white px-3 small text-muted text-uppercase fw-semibold" style="letter-spacing: 0.5px;">Or continue with</span>
                </div> -->

                <!-- <div class="d-grid">
                    <button type="button" class="btn border-light-subtle btn-lg rounded-3 shadow-sm text-dark d-flex align-items-center justify-content-center bg-white google-btn py-2">
                        <i class="bi bi-google text-danger me-2"></i> <span class="fw-medium text-secondary">Sign in with Google</span>
                    </button>
                </div> -->

                <!-- <div class="text-center mt-5">
                  <p class="text-muted small mb-0">Don't have an account? <router-link to="/signup" class="text-primary fw-semibold text-decoration-none">Sign up</router-link></p>
                </div> -->
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
